// 101 Street Quotes
const QUOTES = [
  { id: 1, ot: "Journey of thousand miles start wit transport money." },
  {
    id: 2,
    ot: "Life na mathematics, if you no hustle, sapa go dey constant.",
  },
  { id: 3, ot: "Make you dey rest and recharge your body." },
  { id: 4, ot: "Show kindness to yourself and people around you." },
  { id: 5, ot: "See challenges as opportunity to grow." },
  { id: 6, ot: "Set clear goals wey you fit achieve." },
  { id: 7, ot: "Dey grateful every day." },
  { id: 8, ot: "Listen well before you talk." },
  { id: 9, ot: "Arrange yourself to reduce stress." },
  { id: 10, ot: "Build strong, better relationships." },
  { id: 11, ot: "Dey present for the moment wey you dey." },
  { id: 12, ot: "Learn from your mistakes." },
  { id: 13, ot: "Celebrate even small wins." },
  { id: 14, ot: "Drink water and chop better food." },
  { id: 15, ot: "Find time do wetin dey make you happy." },
  { id: 16, ot: "Dey waka comot your comfort zone sometimes." },
  { id: 17, ot: "No fear to ask for help when you need am." },
  { id: 18, ot: "Dey think positive always." },
  { id: 19, ot: "Plan your day before you sleep." },
  { id: 20, ot: "Breathe well when stress wan catch you." },
  { id: 21, ot: "Surround yourself with positive vibes." },
  { id: 22, ot: "Read book to learn new things." },
  { id: 23, ot: "Help your community." },
  { id: 24, ot: "Trust the timing of your life." },
  { id: 25, ot: "Get patience with yourself and others." },
  { id: 26, ot: "Learn to say “no” without feeling bad." },
  { id: 27, ot: "Spend time for nature to clear your head." },
  { id: 28, ot: "Dey listen well well when people dey talk." },
  { id: 29, ot: "Ask for feedback so you fit improve." },
  { id: 30, ot: "Focus on solution, no be problem." },
  { id: 31, ot: "No give up; keep at it." },
  { id: 32, ot: "Take care of your mental health." },
  { id: 33, ot: "Dey laugh often and enjoy small small things." },
  { id: 34, ot: "Follow your passion with all your heart." },
  { id: 35, ot: "Dey honest with yourself and others." },
  { id: 36, ot: "Value quality over quantity for relationships." },
  { id: 37, ot: "Take time reflect on yourself." },
  { id: 38, ot: "Focus on things wey matter pass." },
  { id: 39, ot: "Find lessons for your failures." },
  { id: 40, ot: "Learn how to adapt to change." },
  { id: 41, ot: "Invest in your personal growth." },
  { id: 42, ot: "Accept responsibility for wetin you do." },
  { id: 43, ot: "Leave wetin you no fit control." },
  {
    id: 44,
    ot: "Start your morning with a routine wey go help you succeed.",
  },
  {
    id: 45,
    ot: "Focus on wetin you fit give, no be just wetin you fit collect.",
  },
  { id: 46, ot: "Take break so you no go burn out." },
  { id: 47, ot: "Dey open to new ideas and perspectives." },
  { id: 48, ot: "Work smart, no be say you go just work hard." },
  { id: 49, ot: "Growth no be today-today thing; e dey take time." },
  { id: 50, ot: "Dey careful with your words and actions." },
  { id: 51, ot: "Develop habits wey go help you reach your goals." },
  { id: 52, ot: "Treat people the way you want make dem treat you." },
  { id: 53, ot: "Enjoy the journey, no be only the destination." },
  { id: 54, ot: "Learn how to forgive yourself and others." },
  { id: 55, ot: "Keep journal to write your thoughts and progress." },
  { id: 56, ot: "Believe for yourself say you fit do am." },
  { id: 57, ot: "Hold on to your values strong strong." },
  { id: 58, ot: "No dey compare yourself with others." },
  { id: 59, ot: "Celebrate other people achievements." },
  { id: 60, ot: "Manage your time well." },
  { id: 61, ot: "Dey proactive, no just dey wait react." },
  { id: 62, ot: "Take care of your body well well." },
  { id: 63, ot: "Focus on wetin really matter." },
  { id: 64, ot: "Dey intentional with wetin you dey do." },
  { id: 65, ot: "Embrace uncertainty, no fear am." },
  { id: 66, ot: "Find mentors and role models to learn from." },
  { id: 67, ot: "Humble yourself and ready to learn." },
  { id: 68, ot: "Show empathy for everything you dey do." },
  { id: 69, ot: "Create vision for your future." },
  { id: 70, ot: "Be proud of wetin you don achieve." },
  { id: 71, ot: "Dey generous with your time and resources." },
  { id: 72, ot: "Stay grounded when wahala come." },
  { id: 73, ot: "Dey keep your promises." },
  { id: 74, ot: "No fear to start afresh." },
  { id: 75, ot: "Learn to enjoy the process." },
  { id: 76, ot: "Take risks, but think am well before you do." },
  { id: 77, ot: "Dey learn till you grow old." },
  { id: 78, ot: "Never lose your sense of wonder." },
  { id: 79, ot: "Respect other people opinions." },
  { id: 80, ot: "Take responsibility for your own happiness." },
  { id: 81, ot: "Discipline yourself for your daily life." },
  { id: 82, ot: "Dey mindful of how you dey spend your money." },
  {
    id: 83,
    ot: "Focus on creating memories, no be just to gather things.",
  },
  { id: 84, ot: "Learn to control your emotions well." },
  { id: 85, ot: "Stay curious about wetin dey around you." },
  { id: 86, ot: "Encourage people make dem be their best." },
  { id: 87, ot: "Take the first step to pursue your dreams." },
  { id: 88, ot: "Be the positivity wey people need." },
  { id: 89, ot: "Create system wey go support your goals." },
  { id: 90, ot: "Trust yourself and your instincts." },
  { id: 91, ot: "Learn to let go of grudges." },
  { id: 92, ot: "Be consistent with wetin you dey do." },
  { id: 93, ot: "Focus on wetin you fit control." },
  { id: 94, ot: "Celebrate even small progress." },
  { id: 95, ot: "Get patience for the process." },
  { id: 96, ot: "Value experiences more than material things." },
  { id: 97, ot: "Learn from people wey dey inspire you." },
  { id: 98, ot: "Keep growth mindset for everything you do." },
  { id: 99, ot: "Take time to appreciate the present moment." },
  { id: 100, ot: "Always dey strive to improve yourself." },
  { id: 101, ot: "Focus on progress, no be perfection." },
  { id: 102, ot: "No use your last card take impress people wey no care." },
  { id: 103, ot: "Person wey no hustle no suppose dey complain." },
  { id: 104, ot: "If you no fit endure, you no go fit enjoy." },
  { id: 105, ot: "Big boys no dey shout, na moves dem dey make." },
  { id: 106, ot: "No carry another person mata for head like gala." },
  { id: 107, ot: "Make sure say your vibe match your hustle." },
  { id: 108, ot: "If plan A no work, na alphabet full ground." },
  { id: 109, ot: "No dey reason wetin no concern your pocket." },
  { id: 110, ot: "Your circle fit dey hold you back, check am." },
  { id: 111, ot: "Loyalty no be by mouth, na by action." },
  { id: 112, ot: "Free things fit cost pass wetin you buy." },
  { id: 113, ot: "No use today play if you want chop tomorrow." },
  { id: 114, ot: "Your vibe fit dey scare people wey no get vision." },
  { id: 115, ot: "Keep your plans coded until e don click." },
  { id: 116, ot: "No dey expect respect if you no dey give am." },
  { id: 117, ot: "Wahala no dey finish, choose your own wisely." },
  { id: 118, ot: "Focus on your lane, traffic dey for other people side." },
  { id: 119, ot: "Person wey no support you no deserve your energy." },
  { id: 120, ot: "Street no soft, but sense go help you survive." },
  { id: 121, ot: "Better no dey rush, e go come when e suppose come." },
  { id: 122, ot: "No be everything wey shine na gold." },
  { id: 123, ot: "No let cruise carry you go where you no suppose dey." },
  { id: 124, ot: "If you no wise, person go use you play." },
  { id: 125, ot: "Success no dey come from noise, na focus work am." },
  { id: 126, ot: "No be who first start dey always finish first." },
  { id: 127, ot: "Street OT no complete if you no dey loyal to yourself." },
  { id: 128, ot: "Make sure say your hustle dey legit, peace sweet pass." },
  {
    id: 129,
    ot: "Your network fit be your net worth, choose people wisely.",
  },
  { id: 130, ot: "If you dey fear failure, success go dey far from you." },
  { id: 131, ot: "No dey loud your move, result go speak." },
  {
    id: 132,
    ot: "No let social media tension you, real life pass that one.",
  },
  { id: 133, ot: "Person wey no dey learn no go fit grow." },
  { id: 134, ot: "No dey compete with who no even notice you." },
  { id: 135, ot: "Street no soft, but na sense go make am smooth." },
  { id: 136, ot: "If you wan enjoy, you go gats endure first." },
  { id: 137, ot: "Run your own race, no follow crowd." },
  { id: 138, ot: "No borrow problem wey no concern you." },
  { id: 139, ot: "Keep your enemies close, but your money closer." },
  { id: 140, ot: "No use your energy follow person wey no send you." },
  { id: 141, ot: "Street OT no complete if you no get patience." },
  { id: 142, ot: "If you no get plan, you go follow another person plan." },
  { id: 143, ot: "No let your background keep you for ground." },
  { id: 144, ot: "No let temporary setback make you give up." },
  { id: 145, ot: "Hustle wey go pay, no be every hustle." },
  { id: 146, ot: "Your mouth fit put you for trouble, talk less." },
  { id: 147, ot: "Keep your head down, but your game high." },
  { id: 148, ot: "No dey compare your chapter 1 with person chapter 10." },
  { id: 149, ot: "The way you treat people fit be your real worth." },
  { id: 150, ot: "If e too good to be true, check am well." },
  {
    id: 151,
    ot: "Your environment fit shape your mindset, choose wisely.",
  },
  { id: 152, ot: "Hustle dey sweet, but results dey sweeter." },
  { id: 153, ot: "No go enter lane wey no be your size." },
  { id: 154, ot: "Plan well, or regret go dey plan for you." },
  { id: 155, ot: "No dey too quick to trust." },
  { id: 156, ot: "No use your hand block your own blessing." },
  { id: 157, ot: "Street OT no complete if you no dey grateful." },
  { id: 158, ot: "No let your ego stop you from learning." },
  { id: 159, ot: "People go believe you if your actions match your talk." },
  { id: 160, ot: "Money no be everything, but e dey sweet life." },
  { id: 161, ot: "Stay real, no fake am for anybody." },
  { id: 162, ot: "No be everybody wey smile with you be your guy." },
  { id: 163, ot: "Small small, na im e dey enter pot." },
  {
    id: 164,
    ot: "If you no believe for yourself, nobody go believe for you.",
  },
  { id: 165, ot: "Use wetin you get to get wetin you want." },
  { id: 166, ot: "Street OT: Learn to observe more, talk less." },
  { id: 167, ot: "Hustle no dey finish, but rest no go kill you." },
  { id: 168, ot: "Invest in wetin go bring better return tomorrow." },
  { id: 169, ot: "If you too greedy, you fit lose everything." },
  { id: 170, ot: "No go chop wetin your hand never fit reach." },
  { id: 171, ot: "Dey respect people, no matter their level." },
  { id: 172, ot: "If e no work today, no mean say e no go work tomorrow." },
  { id: 173, ot: "You go gats bend sometimes to stand strong later." },
  {
    id: 174,
    ot: "No dey explain your dream to people wey no understand am.",
  },
  { id: 175, ot: "Person wey no dey take risk no go fit gain." },
  { id: 176, ot: "Keep your mindset sharp; street no be playground." },
  { id: 177, ot: "No let person downgrade you, know your worth." },
  { id: 178, ot: "Street OT: Na results dem dey respect pass noise." },
  { id: 179, ot: "No use today play; na tomorrow you go regret am." },
  { id: 180, ot: "No carry fake vibe enter real zone." },
  { id: 181, ot: "Street no soft, but steady hustle go keep you afloat." },
  { id: 182, ot: "Work on yourself, make your life no be mistake." },
  { id: 183, ot: "Your vibe fit intimidate people, but keep am real." },
  { id: 184, ot: "If you too slow, opportunity go pass you by." },
  { id: 185, ot: "Trust your hustle, but no forget to dey smart." },
  { id: 186, ot: "No give up; your time go come." },
  { id: 187, ot: "Be humble; na street we all dey." },
  { id: 188, ot: "Your attitude fit open door wey money no fit open." },
  { id: 189, ot: "Street OT: Dey move with purpose, no just waka." },
  { id: 190, ot: "Respect yourself; na so people go respect you." },
  { id: 191, ot: "No depend on luck; create your own opportunity." },
  { id: 192, ot: "Street smart pass book smart for survival sometimes." },
  { id: 193, ot: "No follow crowd; create your own lane." },
  { id: 194, ot: "Stay focused; distraction no dey help hustle." },
  { id: 195, ot: "Na street OT: Patience fit save you from wahala." },
  { id: 196, ot: "Make sure say your hand clean for wetin you dey do." },
  { id: 197, ot: "No let frustration push you do wetin you go regret." },
  { id: 198, ot: "Dey learn new skills; e fit be your jackpot tomorrow." },
  { id: 199, ot: "Dey loyal to people wey dey loyal to you." },
  {
    id: 200,
    ot: "No put all your energy for noise; results na im matter.",
  },
  { id: 201, ot: "Make your presence matter even when you no dey around." },
  { id: 202, ot: "Street OT: Grind dey necessary, but balance na key." },
];

const quote = document.querySelector("[data-quote]");
const button = document.querySelector("[data-button]");
let index = (QUOTES.length * Math.random() * Math.random()).toFixed(0);

quote.innerText = QUOTES[index].ot;
button.addEventListener("click", (e) => {
  e.preventDefault();
  let index = (QUOTES.length * Math.random() * Math.random()).toFixed(0);

  quote.innerText = QUOTES[index].ot;
});
