const QUOTES = [
  { id: 1, advice: "Focus on progress, not perfection." },
  { id: 2, advice: "Stay curious and keep learning." },
  { id: 3, advice: "Take time to rest and recharge." },
  { id: 4, advice: "Be kind to yourself and others." },
  { id: 5, advice: "Embrace challenges as opportunities to grow." },
  { id: 6, advice: "Set clear, achievable goals." },
  { id: 7, advice: "Practice gratitude daily." },
  { id: 8, advice: "Listen more than you speak." },
  { id: 9, advice: "Stay organized to reduce stress." },
  { id: 10, advice: "Build strong, supportive relationships." },
  { id: 11, advice: "Be present in the moment." },
  { id: 12, advice: "Learn from your mistakes." },
  { id: 13, advice: "Celebrate small victories." },
  { id: 14, advice: "Stay hydrated and eat nutritious food." },
  { id: 15, advice: "Find time for hobbies you enjoy." },
  { id: 16, advice: "Step outside your comfort zone regularly." },
  { id: 17, advice: "Ask for help when you need it." },
  { id: 18, advice: "Keep a positive mindset." },
  { id: 19, advice: "Plan your day the night before." },
  { id: 20, advice: "Practice deep breathing to manage stress." },
  { id: 21, advice: "Surround yourself with positivity." },
  { id: 22, advice: "Read books to expand your perspective." },
  { id: 23, advice: "Give back to your community." },
  { id: 24, advice: "Trust the timing of your journey." },
  { id: 25, advice: "Be patient with yourself and others." },
  { id: 26, advice: "Learn to say no without guilt." },
  { id: 27, advice: "Spend time in nature to clear your mind." },
  { id: 28, advice: "Practice active listening." },
  { id: 29, advice: "Seek feedback to improve." },
  { id: 30, advice: "Focus on solutions, not problems." },
  { id: 31, advice: "Stay consistent with your efforts." },
  { id: 32, advice: "Take care of your mental health." },
  { id: 33, advice: "Laugh often and find joy in small things." },
  { id: 34, advice: "Pursue your passions with dedication." },
  { id: 35, advice: "Be honest with yourself and others." },
  { id: 36, advice: "Value quality over quantity in relationships." },
  { id: 37, advice: "Make time for self-reflection." },
  { id: 38, advice: "Prioritize tasks that matter most." },
  { id: 39, advice: "Find lessons in failure." },
  { id: 40, advice: "Be adaptable to change." },
  { id: 41, advice: "Invest in your personal growth." },
  { id: 42, advice: "Take responsibility for your actions." },
  { id: 43, advice: "Let go of what you cannot control." },
  { id: 44, advice: "Build a morning routine that sets you up for success." },
  { id: 45, advice: "Focus on what you can give, not just what you can get." },
  { id: 46, advice: "Take breaks to avoid burnout." },
  { id: 47, advice: "Be open to new ideas and perspectives." },
  { id: 48, advice: "Work smarter, not harder." },
  { id: 49, advice: "Remember that growth takes time." },
  { id: 50, advice: "Be mindful of your words and actions." },
  { id: 51, advice: "Develop healthy habits that support your goals." },
  { id: 52, advice: "Treat others as you wish to be treated." },
  { id: 53, advice: "Appreciate the journey, not just the destination." },
  { id: 54, advice: "Practice forgiveness, both for yourself and others." },
  { id: 55, advice: "Keep a journal to track your thoughts and progress." },
  { id: 56, advice: "Believe in your abilities." },
  { id: 57, advice: "Stay true to your values." },
  { id: 58, advice: "Avoid comparing yourself to others." },
  { id: 59, advice: "Celebrate the achievements of others." },
  { id: 60, advice: "Learn to manage your time effectively." },
  { id: 61, advice: "Be proactive, not reactive." },
  { id: 62, advice: "Take care of your physical health." },
  { id: 63, advice: "Focus on the things that truly matter." },
  { id: 64, advice: "Be intentional with your actions." },
  { id: 65, advice: "Learn to embrace uncertainty." },
  { id: 66, advice: "Seek out mentors and role models." },
  { id: 67, advice: "Be humble and open to learning." },
  { id: 68, advice: "Practice empathy in all interactions." },
  { id: 69, advice: "Create a vision for your future." },
  { id: 70, advice: "Take pride in your accomplishments." },
  { id: 71, advice: "Be generous with your time and resources." },
  { id: 72, advice: "Stay grounded during challenging times." },
  { id: 73, advice: "Keep your promises." },
  { id: 74, advice: "Don’t be afraid to start over." },
  { id: 75, advice: "Learn to enjoy the process." },
  { id: 76, advice: "Take risks, but calculate them wisely." },
  { id: 77, advice: "Be a lifelong learner." },
  { id: 78, advice: "Maintain a sense of wonder." },
  { id: 79, advice: "Be respectful of differing opinions." },
  { id: 80, advice: "Take responsibility for your happiness." },
  { id: 81, advice: "Practice discipline in your daily life." },
  { id: 82, advice: "Be mindful of your spending habits." },
  {
    id: 83,
    advice: "Focus on creating memories, not just accumulating things.",
  },
  { id: 84, advice: "Learn to manage your emotions effectively." },
  { id: 85, advice: "Stay curious about the world around you." },
  { id: 86, advice: "Encourage others to achieve their best." },
  { id: 87, advice: "Take the first step toward your dreams." },
  { id: 88, advice: "Be a source of positivity for others." },
  { id: 89, advice: "Create systems that support your goals." },
  { id: 90, advice: "Trust yourself and your instincts." },
  { id: 91, advice: "Learn to let go of grudges." },
  { id: 92, advice: "Be consistent in your efforts." },
  { id: 93, advice: "Focus on the things you can control." },
  { id: 94, advice: "Celebrate progress, no matter how small." },
  { id: 95, advice: "Be patient with the process." },
  { id: 96, advice: "Value experiences over material possessions." },
  { id: 97, advice: "Learn from those who inspire you." },
  { id: 98, advice: "Keep a growth mindset in everything you do." },
  { id: 99, advice: "Take time to appreciate the present." },
  { id: 100, advice: "Always keep striving to improve." },
  {
    id: 101,
    advice: "A journey of a thousand miles starts with transport money.",
  },
];

const id = document.querySelector("[data-id]");
const quote = document.querySelector("[data-quote]");
const button = document.querySelector("[data-button]");
let index = (QUOTES.length * Math.random()).toFixed(0);

id.innerText = QUOTES[index].id;
quote.innerText = QUOTES[index].advice;
button.addEventListener("click", (e) => {
  e.preventDefault();
  let index = (QUOTES.length * Math.random() * Math.random()).toFixed(0);

  id.innerText = QUOTES[index].id;
  quote.innerText = QUOTES[index].advice;
});
